import os

def generate_icon(ostype):
    names = ['logo']
    path = "../platform/" + ostype
    if os.path.isfile(path + "/run_icon.png"):
        names.append('run_icon')

    for name in names:
        pngf = open(path + "/" + name + ".png", "rb")
        b = pngf.read(1)
        str = " /* AUTOGENERATED FILE, DO NOT EDIT */ \n"
        str += " static const unsigned char _" + ostype + "_" + name + "[]={"
        while len(b) == 1:
            str += hex(ord(b))
            b = pngf.read(1)
            if (len(b) == 1):
                str += ","

        str += "};\n"

        pngf.close()

        # NOTE: It is safe to generate this file here, since this is still executed serially
        wf = path + "/" + name + ".gen.h"
        with open(wf, "w") as pngw:
            pngw.write(str)

import sys

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("usage : " + sys.argv[0] + " <os>")
        exit()
    generate_icon(sys.argv[1])